version: 1.0.{build}
image: Visual Studio 2019  # Choose an environment that includes Python 3.10

environment:
  matrix:
    - python: 'C:\\Python310-x64'

install:
  # Add python to PATH
  - 'SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
  - python --version
  # Install python packages
  - python -m pip install --upgrade pip
  - cd py
  - python -m pip install -r requirements.txt
  - python -m pip install -e .
  - cd ..

build: off

test_script:
  - cd py
  - python -m pytest
  - cd ..

artifacts:
  - path: py\dist\*
