# AppVeyor configuration file for a Python project
version: 1.0.{build}
image: Visual Studio 2019  # Choose an environment that includes Python 3.10

environment:
  matrix:
    - PYTHON: "C:\\Python310-x64"

# Cache Python packages to speed up builds
cache:
  - '%PYTHON%\\Lib\\site-packages'

init:
  # Display Python version
  - ECHO %PYTHON%
  - '%PYTHON%\\python.exe --version'

install:
  # Install dependencies
  - 'SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%'
  - '%PYTHON%\\python.exe -m pip install --upgrade pip'
  - '%PYTHON%\\python.exe -m pip install pytest'  # Example: Install pytest
  - '%PYTHON%\\python.exe -m pip install -r requirements.txt'  # Assuming you have a requirements.txt

build_script:
  # Add build script here if needed
  - ECHO "Build step (if necessary)"

test_script:
  # Navigate to the directory containing tests and run them
  - cd project_directory  # Change to the directory with your code
  - '%PYTHON%\\python.exe -m pytest tests'  # Assuming your tests are in the 'tests' directory

artifacts:
  # Specify artifacts to collect
  - path: 'project_directory\\dist\\*'

on_finish:
  # Script that runs after the build process is done
  - ECHO "Build and test process finished."